---
title: "random-seed-analysis"
output: html_document
date: "2025-05-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(lme4)
library(glue)
```

```{r}
losses <- read_csv("losses.csv") %>%
  mutate(seed=factor(seed))
losses.plt <- losses %>%
  ggplot(aes(x = train_loss, y = test_loss)) +
  geom_point() +
  labs(x = "Train Loss", y = "Test Loss", title = "Average Train vs Test Loss for 20 Re-runs") +
  theme_minimal()
ggsave("losses.pdf", losses.plt, width=5, height=3)
```
```{r}
mean_test <- mean(losses$test_loss)
sd_test <- sd(losses$test_loss)
losses$outlier_test <- abs(losses$test_loss - mean_test) > 2 * sd_test

# Train loss outliers
mean_train <- mean(losses$train_loss)
sd_train <- sd(losses$train_loss)
losses$outlier_train <- abs(losses$train_loss - mean_train) > 2 * sd_train
```

```{r}
model <- lm(test_loss~train_loss, data=losses)
summary(model)
```

```{r}
rstandard(model)
```
```{r}
plot(model)
```

```{r}
anova_test <- aov(test_loss ~ factor(seed), data = losses)
summary(anova_test)
```


```{r}
blimp_configs = c('adjunct_island', 'anaphor_gender_agreement', 'anaphor_number_agreement', 'animate_subject_passive', 'animate_subject_trans', 'causative', 'complex_NP_island', 'coordinate_structure_constraint_complex_left_branch', 'coordinate_structure_constraint_object_extraction', 'determiner_noun_agreement_1', 'determiner_noun_agreement_2', 'determiner_noun_agreement_irregular_1', 'determiner_noun_agreement_irregular_2', 'determiner_noun_agreement_with_adj_2', 'determiner_noun_agreement_with_adj_irregular_1', 'determiner_noun_agreement_with_adj_irregular_2', 'determiner_noun_agreement_with_adjective_1', 'distractor_agreement_relational_noun', 'distractor_agreement_relative_clause', 'drop_argument', 'ellipsis_n_bar_1', 'ellipsis_n_bar_2', 'existential_there_object_raising', 'existential_there_quantifiers_1', 'existential_there_quantifiers_2', 'existential_there_subject_raising', 'expletive_it_object_raising', 'inchoative', 'intransitive', 'irregular_past_participle_adjectives', 'irregular_past_participle_verbs', 'irregular_plural_subject_verb_agreement_1', 'irregular_plural_subject_verb_agreement_2', 'left_branch_island_echo_question', 'left_branch_island_simple_question', 'matrix_question_npi_licensor_present', 'npi_present_1', 'npi_present_2', 'only_npi_licensor_present', 'only_npi_scope', 'passive_1', 'passive_2', 'principle_A_c_command', 'principle_A_case_1', 'principle_A_case_2', 'principle_A_domain_1', 'principle_A_domain_2', 'principle_A_domain_3', 'principle_A_reconstruction', 'regular_plural_subject_verb_agreement_1', 'regular_plural_subject_verb_agreement_2', 'sentential_negation_npi_licensor_present', 'sentential_negation_npi_scope', 'sentential_subject_island', 'superlative_quantifiers_1', 'superlative_quantifiers_2', 'tough_vs_raising_1', 'tough_vs_raising_2', 'transitive', 'wh_island', 'wh_questions_object_gap', 'wh_questions_subject_gap', 'wh_questions_subject_gap_long_distance', 'wh_vs_that_no_gap', 'wh_vs_that_no_gap_long_distance', 'wh_vs_that_with_gap', 'wh_vs_that_with_gap_long_distance')
read_blimp_result <- function(seed, blimp_config) {
  res = read_csv(glue("results/blimp_{blimp_config}_{seed}.csv"))
  res$seed = seed
  res$config = blimp_config
  return (res)
}
all_data <- list()  # Initialize an empty list to store data frames
i <- 1  # Index for the list
seed <- c(5345, 7445, 1732, 8720, 4522, 7454, 577, 7429, 5578, 440, 2751, 5731, 5272, 5653, 4000, 4557, 583, 6290, 7051, 4895)

for (s in seed) {
  for (config in blimp_configs) {
    res <- read_blimp_result(s, config)
    all_data[[i]] <- res
    i <- i + 1
  }
}
combined_data <- do.call(rbind, all_data)
```
```{r}
combined_data <- combined_data %>%
  mutate(category=case_when(grepl("anaphor", config)~"Anaphor Agreement",
                            grepl("principle_A", config)~"Binding",
                            grepl("determiner_noun", config)~"Determiner-Noun Agreement",
                            grepl("wh_", config)~"Filler Gap",
                            grepl("irregular", config)~"Irregular Forms",
                            grepl("quantifiers",config)~"Quantifiers",
                            grepl("distractor_agreement", config)~"Subject-Verb Agreement",
                            grepl("subject_verb_agreement", config)~"Subject-Verb Agreement",
                            grepl("npi", config)~"NPI Licensing",
                            grepl("island", config)~"Island Effects",
                            grepl("coordinate_structure", config)~"Island Effects",
                            grepl("ellipsis", config)~"Ellipsis",
                            grepl("raising", config)~"Control/Raising",
                            config %in% c("animate_subject_passive", 
                                          "animate_subject_trans", 
                                          "causative",
                                          "drop_argument",
                                          "inchoative",
                                          "intransitive",
                                          "passive_1",
                                          "passive_2",
                                          "transitive"
                                          ) ~ "Argument Structure"
                            
                            ))
```



### Some Overall Descriptive Statistics
```{r}
library(ggbeeswarm)

accuracy.by.seed <- combined_data %>%
  mutate(seed = factor(seed)) %>%
  group_by(seed) %>% 
  summarize(accuracy=mean(correct)) 

accuracy.by.seed.plt <- accuracy.by.seed %>%
  ggplot(aes(x = "", y = accuracy)) +
  geom_violin(fill = "gray80") +
  geom_boxplot(width=0.5) +
  geom_jitter(width = 0.05, color = "steelblue", size = 2) +
  theme_minimal() +
  labs(
       x = "", y = "Accuracy") 
accuracy.by.seed.plt
ggsave("accuracy.by.seed.pdf", accuracy.by.seed.plt, width=3, height=3)
```

```{r}
gpt2_accuracy <- read_csv("gpt2_accuracy.csv") %>%
  mutate(model = "pretrained",
         accuracy = 0.01 * accuracy)
```

```{r}
average_my_accuracy <- combined_data %>%
  mutate(seed = factor(seed)) %>%
  group_by(category) %>% 
  summarize(accuracy=mean(correct)) 
average_my_accuracy$model <- "self-trained"
```

```{r}
rbind(gpt2_accuracy, average_my_accuracy)
```


```{r}
my.vs.gpt2.plt <- rbind(gpt2_accuracy, average_my_accuracy) %>%
  ggplot(aes(x=accuracy, y=category, fill=model)) +
  geom_bar(stat="identity", position=position_dodge()) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, vjust=0.7),
        legend.position = "bottom") + labs(x = "Accuracy", y="Phenomenon")
my.vs.gpt2.plt
ggsave("my.vs.gpt2.plt.pdf", my.vs.gpt2.plt, width=6, height=6)
```


```{r}
accuracy.by.config<- combined_data %>%
  mutate(seed=factor(seed)) %>%
  group_by(config, seed) %>%
  summarize(accuracy=mean(correct)) %>%
  group_by(config)
accuracy.by.config.plt <- accuracy.by.config %>%
  ggplot(aes(x=config, y=accuracy)) + 
  geom_violin(fill="gray80") + 
  geom_boxplot(width=0.4, outlier.color = "steelblue") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, vjust=0.5))
accuracy.by.category.plt
ggsave("accuracy.by.config.plt.pdf", accuracy.by.config.plt, width=9, height=3.5)
```


```{r}
accuracy.by.category <- combined_data %>%
  mutate(seed=factor(seed)) %>%
  group_by(category, seed) %>%
  summarize(accuracy=mean(correct)) %>%
  group_by(category)
accuracy.by.category.plt <- accuracy.by.category %>%
  ggplot(aes(x=category, y=accuracy)) + 
  geom_violin(fill="gray80") + 
  geom_boxplot(width=0.4, outlier.color = "steelblue") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, vjust=0.5))
accuracy.by.category.plt
ggsave("accuracy.by.category.plt.pdf", accuracy.by.category.plt, width=9, height=3.5)
```
```{r}
accuracy.by.sd <- combined_data %>%
  mutate(seed=factor(seed)) %>%
  group_by(config, seed) %>%
  summarize(accuracy=mean(correct)) %>%
  group_by(config) %>%
  summarize(sd=sd(accuracy), mean_accuracy=mean(accuracy)) 
accuracy.by.sd.plt <- accuracy.by.sd %>%
  ggplot(aes(x = mean_accuracy, y=sd)) +
  geom_point(color="steelblue") + 
  geom_smooth(method='lm', formula= y~x) + 
  labs(x="Accuracy", y="Standard Deviation")
ggsave("accuracy.by.sd.pdf", accuracy.by.sd.plt, width=4, height=3)
summary(lm(sd~mean_accuracy, data=accuracy.by.sd))
```


```{r}
accuracy.by.field <- combined_data %>%
  mutate(seed=factor(seed)) %>%
  group_by(field, seed) %>%
  summarize(accuracy=mean(correct)) %>%
  group_by(field)
accuracy.by.field.plt <- accuracy.by.field %>%
  ggplot(aes(x=field, y=accuracy)) + 
  geom_violin(fill="gray80") + 
  geom_boxplot(width=0.4, outlier.color = "steelblue") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, vjust=0.5))
accuracy.by.field.plt
```

```{r}
accuracy.by.config.seed.plt <- combined_data %>%
  mutate(seed=factor(seed)) %>%
  group_by(config, seed) %>%
  summarize(accuracy=mean(correct)) %>%
  ggplot(aes(x = seed, y = config, fill = accuracy)) +
  geom_tile(color = "white") +
  geom_text(aes(label = sprintf("%.2f", accuracy)), size = 1) + 
  scale_fill_viridis_c(option = "rocket") +
  theme_minimal() +
  labs(x = "Random Seed", y = "Paradigm") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")
ggsave("accuracy.by.config.seed.plt.pdf", accuracy.by.config.seed.plt, height=10, width=6)
```

```{r}
arrange(combined_data %>%
  mutate(seed=factor(seed)) %>%
  group_by(config, seed) %>%
  summarize(accuracy=mean(correct)) %>%
  group_by(config) %>%
  summarize(max_accuracy = max(accuracy),
         min_accuracy = min(accuracy),
         diff=max(accuracy)-min(accuracy)), diff)
```




```{r}
combined_data %>%
  mutate(seed=factor(seed)) %>%
  group_by(config, seed) %>%
  summarize(accuracy=mean(correct)) %>%
  ggplot(aes(x=config, fill=seed, y=accuracy)) + 
  geom_bar(stat="identity", alpha=0.8, position=position_dodge())
```

